version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11-debian-10
    ports:
      - 5432:5432
    volumes:
      - fiber_messenger_postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=vking34
      - POSTGRESQL_PASSWORD=43gnikv
      - POSTGRESQL_DATABASE=messenger_db
      # - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    expose:
         - 6379
    volumes:
      - fiber_messenger_redis_data:/bitnami/redis/data

volumes:
  fiber_messenger_postgresql_data:
    driver: local
  
  fiber_messenger_redis_data:
    driver: local
